name: deprimap-urbanchange
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.9
  - geopandas
  - rasterio
  - numpy
  - shapely
  - joblib
  - tqdm
  - jupyterlab
  - seaborn
  - esda
  - fiona
  - matplotlib-scalebar

